### ISSUE TITLE
Linter crashes due to reference to args.json

### ISSUE THREAD

**Issue by evan-a-a** [flathub/flatpak-builder-lint#183]
In https://github.com/flathub/flatpak-builder-lint/commit/93d267a912fc8d7b97375ca586a6a74f7a6bd7a4 args.json was removed, however the reference on line 148 was missed, and this is now raising `AttributeError`. This issue blocks CI when the linter reports warnings. 

Example: https://buildbot.flathub.org/#/builders/25/builds/8845

**Comment by muelli** [comment]
```
Traceback (most recent call last):
  File "/app/bin/flatpak-builder-lint", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/app/lib/python3.11/site-packages/flatpak_builder_lint/cli.py", line 148, in main
    if args.exceptions and not args.json:
                               ^^^^^^^^^
AttributeError: 'Namespace' object has no attribute 'json'
```

**Comment by hfiguiere** [comment]
We have deployed a fix https://github.com/flathub/org.flatpak.Builder/pull/186 until things are merged.
