### ISSUE TITLE
RuntimeError: Failed to list screenshots (on all archs)

### ISSUE THREAD

**Issue by past-due** [flathub/flatpak-builder-lint#216]
Using the `flatpak-builder-lint` from the current `org.flatpak.Builder` Flatpak now yields the following error (regardless of architecture):

```
Traceback (most recent call last):
  File "/app/bin/flatpak-builder-lint", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/app/lib/python3.11/site-packages/flatpak_builder_lint/cli.py", line 156, in main
    if results := run_checks(args.type, path, args.exceptions, args.appid):
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/lib/python3.11/site-packages/flatpak_builder_lint/cli.py", line 70, in run_checks
    check_method(check_method_arg)
  File "/app/lib/python3.11/site-packages/flatpak_builder_lint/checks/screenshots.py", line 72, in check_repo
    raise RuntimeError("Failed to list screenshots")
RuntimeError: Failed to list screenshots
```

This seems to have broken sometime yesterday(?) for x86_64 (aarch64 previously had this issue).

@barthalion

**Comment by bbhtt** [comment]
Posted a fix, it was passing literal "{arch}" to ostree.
